-- Schema creation
CREATE SCHEMA IF NOT EXISTS LAB_BAC;

-- Table creation
CREATE TABLE IF NOT EXISTS LAB_BAC.PEOPLE
(
    ID            BIGINT       NOT NULL PRIMARY KEY,
    UUID    VARCHAR(64) NOT NULL,
    FIRST_NAME    VARCHAR(512),
    LAST_NAME     VARCHAR(512),
    TITLE         VARCHAR(512),
    MIN_ROLE      VARCHAR(32),
    CREATION_DATE TIMESTAMP
    );

-- Sequence creation
CREATE SEQUENCE IF NOT EXISTS LAB_BAC.SEQ_PEOPLE
    START WITH 10000
    INCREMENT BY 1
    MAXVALUE 99999999999
    CACHE 1;

-- Dati iniziali per Broken Access Control Lab
-- Usa MERGE per evitare errori di chiave duplicata

MERGE INTO LAB_BAC.PEOPLE (ID, UUID, FIRST_NAME, LAST_NAME, TITLE, MIN_ROLE, CREATION_DATE)
    KEY (ID)
    VALUES (10000, '46005e2d-4faa-4c5a-8ed2-6876d63622a7', 'Margherita', 'Hack', 'Astrofisica', null, CURRENT_TIMESTAMP);

MERGE INTO LAB_BAC.PEOPLE (ID, UUID, FIRST_NAME, LAST_NAME, TITLE, MIN_ROLE, CREATION_DATE)
    KEY (ID)
    VALUES (10001, '62472b90-14a5-45b5-891e-14f9e5659680', 'Alan', 'Turing', 'Matematico', null, CURRENT_TIMESTAMP);

MERGE INTO LAB_BAC.PEOPLE (ID, UUID, FIRST_NAME, LAST_NAME, TITLE, MIN_ROLE, CREATION_DATE)
    KEY (ID)
    VALUES (10002, '3ad86124-765a-4104-a2dd-e99335ff1260', 'Richard', 'Feynman', 'Fisico', 'admin', CURRENT_TIMESTAMP);

-- Resetta la sequence al valore successivo
ALTER SEQUENCE LAB_BAC.SEQ_PEOPLE RESTART WITH 10003;
